version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
    - "3030:3030"
    depends_on:
    - "mongo"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=issacnitinmongod
      - MONGO_INITDB_ROOT_PASSWORD=iPhoneMyPh0ne!!
      - MONGO_ROOT_USER=issacnitinmongod
      - MONGO_ROOT_PASS=iPhoneMyPh0ne!!
      - APP_MONGO_USER=issacnitinmongod
      - APP_MONGO_PASS=iPhoneMyPh0ne!!
      - APP_MONGO_DB=torre
    logging:
      driver: "none"