version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
    - "mongo"
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=issacnitinmongod
      - MONGO_INITDB_ROOT_PASSWORD=iPhoneMyPh0ne
      - MONGO_ROOT_USER=issacnitinmongod
      - MONGO_ROOT_PASS=iPhoneMyPh0ne
      - APP_MONGO_USER=issacnitinmongod
      - APP_MONGO_PASS=iPhoneMyPh0ne
      - APP_MONGO_DB=torre
    logging:
      driver: "none"
  nginx: 
    image: nginx:latest
    container_name: dev_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on: 
    - "backend"